title: Styless
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  A modern, highly customizable, and unstyled Jekyll theme with dark mode.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ksengine
github_username:  ksenginew

darkmode: true
reset: true

# Build settings

# for gem based
# theme: styless

# for github pages
remote_theme: moonharelabs/styless@main

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
